app/views/site.py
from flask import Blueprint, render_template, redirect, url_for, flash, jsonify, session, request
from .. import forms
from flask_login import login_user, login_required, logout_user, current_user
from .. import models
import mongoengine as me
from ..helpers.utils import location_list, get_ap_list_with_sla
from ..helpers.api import access_point_list
from .. import oauth2
import datetime

module = Blueprint('site', __name__)


@module.app_context_processor
def account_context():
    return {'account': current_user}


@module.route('/')
def index():
    if current_user.is_authenticated:
        if current_user.role == 'admin':
            return redirect('/admin/overview/access-point')
    response = access_point_list()
    if response is None:
        response = []
    accessPoints = get_ap_list_with_sla(response)
    if not accessPoints:
        accessPoints = []
    return render_template("index.html", title="หน้าหลัก", location_list=location_list(), access_point_list=accessPoints)


@module.route('/get-aps')
def get_aps():
    get_ap_data = access_point_list()
    result = get_ap_list_with_sla(get_ap_data)
    return jsonify(result)


@module.route('/get-ap/<string:accessPoint_id>')
def get_accessPoint(accessPoint_id):
    try:
        times_list = []
        status_list = []
        data_filter = []
        accessPoint_list_ids = []
        now = datetime.datetime.now()
        selected_month = now.month
        selected_year = now.year
        selected_date = now.day
        accessPoint = models.AccessPoint.objects(
            accessPoint_id=accessPoint_id, month=selected_month, year=selected_year).first()
        if accessPoint:

            for accessPoint in accessPoint.accessPoint_list:

                accessPoint_list_ids.append(accessPoint["id"])

            query = models.AccessPointList.objects(id__in=accessPoint_list_ids)
            query_accessPoint_list = query.all()
            

            for hour in range(24):
                for minute in range(0, 60, 10):
                    time_str = f"{hour:02d}:{minute:02d}"
                    times_list.append(time_str)

            for item in query_accessPoint_list:
                created_date = item["created_date"]
                day = created_date.day
                month = created_date.month
                year = created_date.year
                if day == selected_date and month == selected_month and year == selected_year:
                    data_filter.append(item)

            for i in times_list:
                status_list.append(1)

            for item in data_filter:
                last_state = item["last_state"]
                time_add = item["created_date"]
                if last_state != -1 :
                    time_hour = time_add.hour
                    time_minutes = time_add.minute
                    time_hour = time_hour * 6
                    time_minutes = int(time_minutes / 10)
                    time_down = int(item["minutes"] / 10)

                    start_time = time_hour + time_minutes
                    end_time = start_time + time_down

                else :
                    time_hour = time_add.hour
                    time_minutes = time_add.minute
                    time_hour = time_hour * 6
                    time_minutes = int(time_minutes / 10)
                    start_time = time_hour + time_minutes

                    my_datetime = datetime.datetime.now()
                    hour = int(my_datetime.strftime("%H"))
                    minute = int(my_datetime.strftime("%M"))
                    hour = hour * 6
                    minute = int(minute / 10)
                    end_time = hour + minute

                for i in range(start_time, end_time + 1):
                    status_list[i] = 0
                    

            if data_filter:
                my_datetime = datetime.datetime.now()
                hour = int(my_datetime.strftime("%H"))
                minute = int(my_datetime.strftime("%M"))
                


                hour = hour * 6
                minute = int(minute / 10)
                start_time = hour + minute
                end_time = len(status_list)
                
                for i in range(start_time, end_time):
                    status_list[i] = ""

                

            if not data_filter:
                
                if len(query_accessPoint_list) != 0:
                
                    last_state = query_accessPoint_list[len(
                        query_accessPoint_list)-1]["last_state"]
                    if last_state == -1:
                        for i in range(0, 144):
                            status_list[i] = 0

                            
            if not data_filter:
                
                my_datetime = datetime.datetime.now()
                hour = int(my_datetime.strftime("%H"))
                minute = int(my_datetime.strftime("%M"))
                hour = hour * 6
                minute = int(minute / 10)
                start_time = hour + minute
                end_time = len(status_list)

                for i in range(start_time, end_time):
                    status_list[i] = ""

            
                


            x_values = times_list
            y_values = status_list

            return jsonify(x_values, y_values)
        else:
            return jsonify({"error": "AccessPoint not found"}), 404
    except Exception as ex:
        return jsonify({"error": str(ex)}), 500


@module.route('/get-locations')
def getLocations():
    location_data = []
    for location in location_list():
        location_data.append({
            "id": str(location.id),
            "name": location.name,
            "lat": location.lat,
            "lng": location.lng
        })
    return jsonify(location_data)


@module.route('/get-ap-locations')
def get_ap_locations():
    location_data = []
    ap_data = models.AccessPointLocation.objects()
    for item in ap_data:
        location_data.append({
            "name": item.name,
            "lat": item.coordinates[0],
            "lng": item.coordinates[1],
            "floor": item.floor,
            "room": item.room
        })
    return jsonify(location_data)


@module.route('/login')
def login():
    if current_user.is_authenticated:
        if current_user.role == 'admin':
            return redirect('/admin/overview/access-point')
        else:
            return redirect('/')

    client = oauth2.oauth2_client
    scheme = request.environ.get("CONF_URL", "http")
    redirect_uri = url_for("site.auth", _external=True, _scheme=scheme)
    return client.psu_passport.authorize_redirect(redirect_uri)


@module.route('/auth')
def auth():

    client = oauth2.oauth2_client
    try:
        token = client.psu_passport.authorize_access_token()
    except Exception as e:
        return redirect(url_for("site.login"))
    session['user'] = token['userinfo']

    user = models.User.objects(
        me.Q(username=session['user'].get("username", ""))
        | me.Q(email=session['user'].get("email", ""))
    ).first()

    if not user:
        user = models.User(
            username=session['user'].get("username"),
            email=session['user'].get("email"),
            first_name=session['user'].get("first_name").title(),
            last_name=session['user'].get("last_name").title(),
            status="active",
        )
        if session['user']["username"].isdigit():
            user.role = "user"

    user.save()

    login_user(user)

    oauth2token = models.OAuth2Token(
        name=client.psu_passport.name,
        user=user,
        access_token=token.get("access_token"),
        token_type=token.get("token_type"),
        refresh_token=token.get("refresh_token", None),
        expires=datetime.datetime.utcfromtimestamp(token.get("expires_in")),
    )
    oauth2token.save()

    next_uri = session.get("next", None)
    if next_uri:
        session.pop("next")
        return redirect(next_uri)
    return redirect(url_for("site.index"))


@module.route('/logout')
@login_required
def logout():
    logout_user()
    session.clear()
    client = oauth2.oauth2_client
    remote = client.psu_passport
    logout_url = f"{ remote.server_metadata.get('end_session_endpoint') }?redirect={ request.scheme }://{ request.host }"
    if logout_url:
        return redirect(logout_url)

    return redirect(url_for('site.index'))


@module.route('/report', methods=["GET", "POST"])
def report():
    form = forms.ReportForm()
    if form.validate_on_submit():
        title = form.title.data
        detail = form.detail.data
        lat = form.lat.data
        lng = form.lng.data
        issue_category = form.issue_category.data
        if any(field == "" for field in [title, detail, lat, lng, issue_category]):
            flash("กรุณากรอกข้อมูล/ปักหมุดสถานที่ในแมพ", "error")
            return render_template("report.html", title="รายงานปัญหา", form=form)
        report = models.Report(
            title=title,
            detail=detail,
            lat=round(float(lat), 6),
            lng=round(float(lng), 6),
            reported_by=current_user,
            category=issue_category
        )
        report.save()
        flash("บันทึกสำเร็จ", "success")
        form.title.data = ""
        form.detail.data = ""
        form.lat.data = ""
        form.lng.data = ""
        form.issue_category.data = ""

    if not current_user.is_authenticated:
        return redirect('/login')

    return render_template("report.html", title="รายงานปัญหา", form=form)


@module.route('/history', methods=["GET", "POST"])
def report_history():
    if not current_user.is_authenticated:
        return redirect('/login')
    reports = models.Report.objects(reported_by=current_user.id)
    return render_template("reportHistory.html", title="ประวัติรายงานปัญหา", reports=reports)

app/templates/layouts/accessPointModal.html
<dialog id="ap-modal" class="modal">
  <form method="dialog" class="modal-box w-11/12 max-w-5xl">
    <h3 class="font-bold text-lg" id="ap-title"></h3>
    <div class="modal-tabs tabs pt-5">
      <a class="tab tab-lifted tab-active" data-tab="ap-info">Info</a>
    </div>
    <div id="ap-info" class="modal-section current">
      <p id="ap-info-detail" class="py-4"></p>
      <p id="ap-graph-detail" class="py-4 pr-2"></p>
    </div>
  </form>
  <form method="dialog" class="modal-backdrop">
    <button onclick="handleClose()">close</button>
  </form>
</dialog>

<script>
  function handleClose() {
    const modal = document.getElementById("ap-info");
    modal.style.display = "none";
  }
</script>

app/templates/layouts/adminLayout.html
<header class="header dark:bg-base-100">
  <div class="header_container">
    <div class="header_img flex gap-5" style="align-items: center">
      <li class="pr-3">
        <a
          id="link-report"
          class="hover:text-neutral-500 dark:hover:text-white"
          href="/report"
          >แจ้งปัญหา</a
        >
      </li>
      <div>
        <span class="hover:text-white"
          ><input class="checkbox" type="checkbox" id="toggle" />
          <label class="toggle toggle-mode" for="toggle">
            <i class="bx bx-sun icon icon--light"></i>
            <i class="bx bx-moon icon icon--dark"></i>
            <span class="ball"></span> </label
        ></span>
      </div>
      <div class="dropdown dropdown-end" id="ddl-account-admin">
        <label tabindex="0" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <img src="{{ url_for('static', filename='/images/avatar.png') }}" />
          </div>
        </label>
        <ul
          tabindex="0"
          class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow dark:bg-base-100 rounded-box w-52 bg-white"
        >
          <li>
            <div class="p-3 flex flex-col">
              <span style="width: 100%; font-size: 16px"
                >{{ account.first_name }} {{ account.last_name }}</span
              >
              <span
                class="text-neutral-500"
                style="width: 100%; font-size: 13px"
                >{{ account.email }}</span
              >
            </div>
          </li>
          <li>
            <a
              id="btn-logout-admin"
              class="text-red-500 hover:text-white hover:bg-red-500 pb-2"
              href="{{ url_for('site.logout') }}"
              >Logout</a
            >
          </li>
        </ul>
      </div>
    </div>
    <a
      href="{{ url_for('admin.access_point_dashboard') }}"
      class="header_logo dark:text-white"
      >Network Monitoring System</a
    >

    <div class="header_toggle">
      <label class="btn btn-circle swap swap-rotate" id="header-toggle">
        <input type="checkbox" id="toggle-swap" />

        <svg
          class="swap-off fill-current"
          xmlns="http://www.w3.org/2000/svg"
          width="32"
          height="32"
          viewBox="0 0 512 512"
        >
          <path
            d="M64,384H448V341.33H64Zm0-106.67H448V234.67H64ZM64,128v42.67H448V128Z"
          />
        </svg>

        <svg
          class="swap-on fill-current"
          xmlns="http://www.w3.org/2000/svg"
          width="32"
          height="32"
          viewBox="0 0 512 512"
        >
          <polygon
            points="400 145.49 366.51 112 256 222.51 145.49 112 112 145.49 222.51 256 112 366.51 145.49 400 256 289.49 366.51 400 400 366.51 289.49 256 400 145.49"
          />
        </svg>
      </label>
    </div>
  </div>
</header>

<div class="nav dark:bg-base-200" id="navbar">
  <nav class="nav_container">
    <div>
      <a
        href="{{ url_for('admin.access_point_dashboard') }}"
        class="nav_link pb-10"
        ><img
          src="{{ url_for('static', filename='/images/psu.png') }}"
          alt="logo"
          width="50"
          height="50"
          class="nav_icon"
          id="logo"
        />
        <span class="nav_logo-name pl-3">DASHBOARD</span></a
      >

      <div class="nav_list pt-8">
        <div class="nav_items">
          <h3 class="nav_subtitle">Pages</h3>

          <a
            id="home-link"
            href="{{ url_for('admin.access_point_dashboard') }}"
            class="nav_link active"
          >
            <i class="bx bx-home nav_icon"></i>
            <span class="nav_name">Home</span>
          </a>
          <div id="ddl-downtime-interval" class="nav_dropdown">
            <a class="nav_link">
              <i class="bx bx-timer nav_icon"></i>
              <span class="nav_name">Duration</span>
              <i class="bx bx-chevron-down nav_icon nav_dropdown-icon"></i>
            </a>

            <div class="nav_dropdown-collapse dark:bg-base-200">
              <div class="nav_dropdown-content">
                <a
                  id="downHosts-link"
                  href="{{ url_for('admin.downHosts') }}"
                  class="nav_dropdown-item pb-4"
                  >Host</a
                >
                <a
                  id="downAccessPoints-link"
                  href="{{ url_for('admin.downAccessPoints') }}"
                  class="nav_dropdown-item"
                  >Access Point</a
                >
              </div>
            </div>
          </div>
          <div id="ddl-host-service" class="nav_dropdown">
            <a class="nav_link">
              <i class="bx bx-line-chart nav_icon"></i>
              <span class="nav_name">SLA Analytics</span>
              <i class="bx bx-chevron-down nav_icon nav_dropdown-icon"></i>
            </a>

            <div class="nav_dropdown-collapse dark:bg-base-200">
              <div class="nav_dropdown-content">
                <a
                  id="host-link"
                  href="{{ url_for('admin.host_history') }}"
                  class="nav_dropdown-item pb-4"
                  >Host</a
                >
                <a
                  id="service-link"
                  href="{{ url_for('admin.service_history') }}"
                  class="nav_dropdown-item pb-4"
                  >Service</a
                >
                <a
                  id="accessPoint-link"
                  href="{{ url_for('admin.access_point_history') }}"
                  class="nav_dropdown-item"
                  >Access Point</a
                >
              </div>
            </div>
          </div>
        </div>

        <div class="nav_items">
          <h3 class="nav_subtitle">Management</h3>
          <a
            id="sla-config-link"
            href="{{ url_for('admin.sla_configuration') }}"
            class="nav_link"
          >
            <i class="bx bxs-report nav_icon"></i>
            <span class="nav_name">SLA</span>
          </a>
          <div id="ddl-location-menu" class="nav_dropdown">
            <a class="nav_link">
              <i class="bx bx-line-chart nav_icon"></i>
              <span class="nav_name">Location</span>
              <i class="bx bx-chevron-down nav_icon nav_dropdown-icon"></i>
            </a>

            <div class="nav_dropdown-collapse dark:bg-base-200">
              <div class="nav_dropdown-content">
                <a
                  id="location-link"
                  href="{{ url_for('admin.location') }}"
                  class="nav_dropdown-item pb-4"
                  >Map</a
                >
                <a
                  id="accesspoint-location-link"
                  href="{{ url_for('admin.access_point_location') }}"
                  class="nav_dropdown-item pb-4"
                  >Access Point</a
                >
                <a
                  id="host-location-link"
                  href="{{ url_for('admin.host_location') }}"
                  class="nav_dropdown-item"
                  >Host</a
                >
              </div>
            </div>
          </div>
          <a
            id="problem-link"
            href="{{ url_for('admin.category') }}"
            class="nav_link"
          >
            <i class="bx bx-category nav_icon"></i>
            <span class="nav_name">Issue Category</span>
          </a>
          <a
            id="permission-link"
            href="{{ url_for('admin.permission') }}"
            class="nav_link"
          >
            <i class="bx bx-group nav_icon"></i>
            <span class="nav_name">Permission</span>
          </a>
          <a
            id="report-link"
            href="{{ url_for('admin.report') }}"
            class="nav_link"
          >
            <i class="bx bx-bug nav_icon"></i>
            <span class="nav_name">Report</span>
          </a>
        </div>
      </div>
    </div>

    <a
      id="logout-sidebar-link"
      href="{{ url_for('site.logout') }}"
      class="nav_link nav_logout"
    >
      <i class="bx bx-log-out nav_icon"></i>
      <span class="nav_name">Log Out</span>
    </a>
  </nav>
</div>

<script src="{{ url_for('static', filename='js/navigation.js') }}"></script>

app/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="{{ url_for('static', filename='js/modeSystem.js') }}"></script>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/favicon.ico') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='node_modules/boxicons/css/boxicons.min.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/output.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/main.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='src/dataTable/print_datatables.min.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='src/dataTable/dataTables.bootstrap.min.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='node_modules/leaflet/dist/leaflet.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='node_modules/datatables.net-dt/css/jquery.dataTables.min.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='node_modules/leaflet.locatecontrol/dist/L.Control.Locate.min.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='node_modules/leaflet.markercluster/dist/MarkerCluster.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='node_modules/leaflet.markercluster/dist/MarkerCluster.Default.css') }}"
    />

    <script src="{{ url_for('static', filename='node_modules/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ url_for('static', filename='src/dataTable/buttons_datatables.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/leaflet/dist/leaflet.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/leaflet.locatecontrol/dist/L.Control.Locate.min.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/leaflet.markercluster/dist/leaflet.markercluster-src.js') }}"></script>
    <script src="{{ url_for('static', filename='node_modules/leaflet.markercluster/dist/leaflet.markercluster.js') }}"></script>
    <!-- <script src="{{ url_for('static', filename='node_modules/leaflet.markercluster/src/MarkerCluster.js') }}"></script> -->
    <script src="https://cdn.plot.ly/plotly-2.26.0.min.js" charset="utf-8"></script>
    <script src="{{ url_for('static', filename='utils/handleLimitLength.js') }}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  
    {% if title %}
    <title>PSU - {{ title }}</title>
    {% else %}
    <title>PSU Network Monitoring</title>
    {% endif %}
  </head>
  <body>
    <div class="loader-wrapper">
      <div class="loader">
        <div class="loader-text">LOADING...</div>
        <div class="loader-bar"></div>
      </div>
    </div>
    {% if account.role == 'admin' %} {% include "/layouts/adminLayout.html" %}
    {% else %} {% include "/layouts/userLayout.html" %} {% endif %}
    <main class="container" style="margin-top: 2rem">
      {% block content %} {% endblock %}
    </main>
    <button
      class="btn fixed bottom-5 end-8 hidden bg-neutral-800 dark:bg-white hover:dark:bg-white hover:bg-neutral-800"
      onclick="scrollToTop()"
      id="back-to-up"
    >
      <i class="bx bxs-chevrons-up text-white dark:text-black text-xl"></i>
    </button>
    <script>
      $(window).on("load", function () {
        $(".loader-wrapper").fadeOut("slow");
      });
    </script>
    <script>
      function fadeOutElement() {
        $(".alert-message").fadeOut(1000);
      }

      setTimeout(fadeOutElement, 5000);
    </script>
    <script>
      window.onscroll = () => {
        toggleTopButton();
      };
      function scrollToTop() {
        window.scrollTo({ top: 0, behavior: "smooth" });
      }

      function toggleTopButton() {
        if (
          document.body.scrollTop > 20 ||
          document.documentElement.scrollTop > 20
        ) {
          document.getElementById("back-to-up").classList.remove("hidden");
        } else {
          document.getElementById("back-to-up").classList.add("hidden");
        }
      }
    </script>
  </body>
</html>

app/templates/layouts/hostModal.html
<dialog id="host-modal" class="modal">
  <form method="dialog" class="modal-box w-11/12 max-w-5xl">
    <h3 class="font-bold text-lg" id="host-title"></h3>
    <div class="modal-tabs tabs pt-5">
      <a class="tab tab-lifted tab-active" data-tab="host-info">Info</a>
    </div>
    <div id="host-info" class="modal-section current">
      <p id="host-info-detail" class="py-4"></p>
      <p id="host-graph-detail" class="py-4 pr-2"></p>
    </div>
  </form>
  <form method="dialog" class="modal-backdrop">
    <button onclick="handleClose()">close</button>
  </form>
</dialog>

<script>
  function handleClose() {
    const modal = document.getElementById("host-info");
    modal.style.display = "none";
  }
</script>

app/templates/layouts/messageSection.html
{% with messages = get_flashed_messages(with_categories=true) %} {% if messages
%} {% for category, message in messages %}
<div id="alert-message" class="alert-message alert alert-{{ category }} mb-4">
  <svg
    xmlns="http://www.w3.org/2000/svg"
    class="stroke-current shrink-0 h-6 w-6"
    fill="none"
    viewBox="0 0 24 24"
  >
    <path
      stroke-linecap="round"
      stroke-linejoin="round"
      stroke-width="2"
      d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
    />
  </svg>
  <span>{{ message }}</span>
</div>
{% endfor %} {% endif %} {% endwith %}

app/templates/layouts/userLayout.html
<div class="navbar bg-navbar dark:bg-base-100 dark:border-b-2 border-gray-800">
  <div class="flex-1">
    <a href="/" class="btn btn-ghost normal-case text-xl"
      ><img
        src="{{ url_for('static', filename='/images/psu.png') }}"
        alt="logo"
        width="55"
        height="30"
        id="logo"
    /></a>
  </div>
  <div class="flex-none">
    <ul
      class="menu menu-horizontal px-1 text-white"
      style="align-items: center"
    >
      <li>
        <span class="hover:text-white"
          ><input class="checkbox" type="checkbox" id="toggle" />
          <label class="toggle toggle-mode" for="toggle">
            <i class="bx bx-sun icon icon--light"></i>
            <i class="bx bx-moon icon icon--dark"></i>
            <span class="ball"></span> </label
        ></span>
      </li>
      <li class="pr-3">
        <a id="link-report" class="hover:text-white" href="/report"
          >แจ้งปัญหา</a
        >
      </li>
      {% if account.is_authenticated %}
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="btn btn-ghost btn-circle avatar">
          <div class="w-10 rounded-full">
            <img src="{{ url_for('static', filename='/images/avatar.png') }}" />
          </div>
        </label>
        <ul
          tabindex="0"
          class="menu menu-sm dropdown-content mt-3 z-[1] p-2 shadow dark:bg-base-100 dark:text-white text-black rounded-box w-52 bg-white"
        >
          <li>
            <div class="p-3 flex flex-col">
              <span style="width: 100%; font-size: 16px"
                >{{ account.first_name }} {{ account.last_name }}</span
              >
              <span class="text-neutral-500" style="width: 100%; font-size: 13px;"
                >{{ account.email }}</span
              >
            </div>
          </li>
          <li></li>
          <li>
            <a
              class="text-red-500 hover:text-white hover:bg-red-500 pb-2"
              href="{{ url_for('site.logout') }}"
              >Logout</a
            >
          </li>
        </ul>
      </div>
      {% else %}
      <li>
        <a
          id="link-login"
          class="border outline outline-2 hover:bg-white hover:text-black"
          href="/login"
          >เข้าสู่ระบบ</a
        >
      </li>
      {% endif %}
    </ul>
  </div>
</div>